### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by agagelin** [agagelin/genome-k-mer#2]
- Comparaison distance pour retrouver le génome d'origine d'un gène :+1: 
    - [x] Calculer les spectre du génome de chaque espèce.
    - [ ] Script de comparaison pour plusieurs K.
- Machine learning (régression logistique) :
    - [ ] Faire un modèle qui apprend sur chaque génome entier.
    - [ ] Créer des datasets de spectre de gène qui prennent une taille réaliste en mémoire.
    - [ ] Apprendre sur ces datasets.
- Faire un Arbre ?
- Trouver des papiers qui documentent les transfers horizontaux ?
